### ISSUE TITLE
Sundown on nginx

### ISSUE THREAD

**Issue by n1c01a5** [vmg/sundown#153]
I have installed sundown with `pecl install sundown`. It's works. And I have unebled sundown in the configuration with `extension=sundown.so` in `/etc/php5/fpm/php.ini` and restart nginx. But the extension don't display in `phpinfo()` and don't works. 

Any idea?

**Comment by FSX** [comment]
You should go here: https://github.com/chobie/php-sundown

That's the repository for php-sundown, the PHP extension. This repository has nothing to do with PHP.

**Comment by n1c01a5** [comment]
It's works now. I don't know why. 
Thanks for your help.

**Comment by n1c01a5** [comment]
We must restart the services `php-fpm` and `nginx`.
