### ISSUE TITLE
Please add render/html.o to libupskirt

### ISSUE THREAD

**Issue by postmodern** [vmg/sundown#16]
I'm working on [ffi-upskirt](http://github.com/postmodern/ffi-upskirt), which uses FFI to access the exported symbols in `libupskirt.so`. I noticed that `render/html.o` is not included in the `libupskirt.so` library. I would like to access the `upshtml_*` functions.

**Comment by vmg** [comment]
Done! Thanks for the heads up!

Loving those bindings, by the way. Just added them to the README.
