### ISSUE TITLE
Add upskirt_version function and UPSKIRT_VERSION constant

### ISSUE THREAD

**Issue by postmodern** [vmg/sundown#17]
It would be very helpful to other bindings, if a `upskirt_version` function (useful for FFI bindings) and an `UPSKIRT_VERSION` constant (useful for C extensions) were added.

**Comment by vmg** [comment]
Done! Check `ups_version`. I hope that's what you needed.

**Comment by postmodern** [comment]
Ah interesting. Ok I can work with that.
