### ISSUE TITLE
Autolink issues

### ISSUE THREAD

**Issue by nono** [vmg/sundown#31]
Hi,

it seems like that upskit doesn't detect some links like http://www-cs-faculty.stanford.edu/ (minus or accent in the subdomain?). Both Rinku and Redcarpet fails to autolink it, so I think the issue come from upskirt.

**Comment by vmg** [comment]
Indeed, dashes on domain names were being treated as invalid characters.

This has been fixed now on Upskirt, Redcarpet and Rinku.

Cheers,
Vicent Marti

On Sun, Jun 19, 2011 at 6:04 PM, nono
reply@reply.github.com
wrote:

**Comment by nono** [comment]
Thanks for your great reactivity!
