### ISSUE TITLE
Misparsing when section header has a prefix numeral

### ISSUE THREAD

**Issue by finsprings** [vmg/sundown#37]
I just got a report from a user who has the following Markdown 

<pre>

1. First Section Title
----------------------------------------------------------------

* First list item.
* Second list item.
* Third list item.

2. Second Section Title
-----------------------------------------------------

A sentence in the second section.

</pre>

This renders properly in TextMate's Markdown preview but with upskirt the numbers in the section titles throw it off. If I remove those numbers it renders how I would expect.

**Comment by vmg** [comment]
Heh, sorry for the delay. I finally got around to closing some of these bug reports. Pushed now the fix, thanks for spotting this!

**Comment by finsprings** [comment]
Excellent, thanks!
