### ISSUE TITLE
Nested parenthesis in href breaks inline hyperlinks

### ISSUE THREAD

**Issue by brandonc** [vmg/sundown#45]
A tricky edge case is parenthesis inside inline urls. Sundown and github flavored markdown both seem to stop on the first occurrence of `)`
- `[inline hyperlink with a paren](http://www.example.com/test#nav(1))`
   [inline hyperlink with a paren](http://www.example.com/test#nav%281%29)
- `[reference hyperlink with paren][1]`
   [reference hyperlink with paren](http://www.example.com/test#nav%281%29)

Perhaps this can be fixed by counting nested parenthesis?

**Comment by vmg** [comment]
Hey Brandon,

the Markdown standard defines that any "active" characters that need to retain their literal values must be prefixed with a `backslash`, i.e. escaped. Parentheses clearly fall under this category.

```
[the Pogo](http://en.wikipedia.org/wiki/Pogo_\(dance\))
```

Let's dance [the Pogo](http://en.wikipedia.org/wiki/Pogo_%28dance%29). Pogo pogo pogo pogo pogo pogo. Note that the first backslash in the opening parenthesis is not required, it's there for completeness.

Cheers!

**Comment by brandonc** [comment]
Thanks for the clarification!
