### ISSUE TITLE
TOC does not ignore headers in fenced code blocks

### ISSUE THREAD

**Issue by FSX** [vmg/sundown#48]
When generating a table of contents all the headers in fenced code blocks are listed too.

See "Header one" and "Header two" in the TOC: http://misaka.61924.nl/. And you can see both headers in the 4th code block under **Usage**.  This is the source file: https://github.com/FSX/misaka/blob/master/docs/documentation.md

**Comment by vmg** [comment]
Hm. Right on, that's because the TOC renderer needs to be run with the same flags as the normal renderer. Have you tried passing the `FENCED_CODE_BLOCKS` extension to `sd_markdown` with the TOC renderer?

**Comment by FSX** [comment]
That worked, thanks. I wasn't passing any extension parameters with the TOC function. Didn't think it would make a difference.

That'll be another bugfix release tomorrow.
