### ISSUE TITLE
inconsistent link rendering in README vs. file

### ISSUE THREAD

**Issue by sunaku** [vmg/sundown#5]
Hello,

I find that markdown links that have newlines in the URL are not rendered properly in the [README on a project's root](https://github.com/sunaku/wmiirc#readme) (search for "my personal configuration file").  In contrast, they _are_ rendered correctly when the [README file is viewed by itself](https://github.com/sunaku/wmiirc/blob/master/README.md) (search for "my personal configuration file").

Here is the markdown source for the link I'm talking about:

``` markdown
* Edit `~/.wmii/config.yaml` to your liking. For a real-life example,
  see [my personal configuration file](
  http://github.com/sunaku/wmiirc/blob/personal/config.yaml).
```

Thanks for your consideration.

**Comment by vmg** [comment]
Fixed! We'll be rolling out the new version soon. Thanks for reporting!
