### ISSUE TITLE
A question about null in mkd_renderer

### ISSUE THREAD

**Issue by txdv** [vmg/sundown#50]
If I supply null in the mkd_renderer for a function, will it just mirror the input or omit it completely?

**Comment by vmg** [comment]
Hey, as the documentation in the header says, for block-level callbacks, a NULL pointer will prevent the block from being rendered, and for span-level callbacks, a NULL pointer will mirror the output verbatim.

**Comment by txdv** [comment]
Hm that makes it a little bit inconvenient - for I HAVE to set all the fields in C# to not null in order to make the api have a subclassing based style.

Basically I have to reimplement the mirroring.
