### ISSUE TITLE
Issue with nested strong/em.

### ISSUE THREAD

**Issue by uhnomoli** [vmg/sundown#56]
```
__foo[___bar___]__
**foo[***bar***]**
```

Is being rendered as:

```
<strong>foo[</strong><em>bar__</em>]__
```

instead of:

```
<strong>foo[</strong><em>bar</em><strong>]</strong>
```

Note, mixing asterisks and underscores works as intended though.

```
__foo[__*bar*__]__
**foo[**_bar_**]**
```

**Comment by vmg** [comment]
Wow, that was heuh... Kind of a corner case. ^^

Just pushed the fix. Sorry this took so long, I've been busy. Cheers!
