### ISSUE TITLE
autolink_url fails and autolink_www takes over when text runs into link

### ISSUE THREAD

**Issue by spladug** [vmg/sundown#73]
```
This text has a lack of spaceshttp://www.google.com
```

renders as

```
<p>This text has a lack of spaceshttp://<a href="http://www.google.com">www.google.com</a></p>
```

rather than

```
<p>This text has a lack of spaces<a href="http://www.google.com">http://www.google.com</a></p>
```

**Comment by vmg** [comment]
Do we really want to match _that_? No other autolinking algorithm does it -- I guess because it looks ugly as hell.

**Comment by spladug** [comment]
This came from the testing against reddit's discount, so discount does this at least.  I agree it's ugly, but the current rendered output is somewhat confusing to an end user.
