### ISSUE TITLE
Underscores in URLs end the link

### ISSUE THREAD

**Issue by franzliedke** [vmg/sundown#9]
Check the link in this issue:
https://github.com/ginatrapani/ThinkUp/issues/728

It looks like the new parser ignores underlines in URLs.

**Comment by vmg** [comment]
Hey Franz, thanks for reporting!

That was a bug in one of the first versions of Redcarpet we deployed. It's been fixed for a while now, but that specific issue page was being rendered from Memcache, and was showing the old HTML. I've just reset the cache and it's working neat right now.

Cheers!

**Comment by franzliedke** [comment]
Ah, thank you very much.

Did you check my profile to call me by my first name? ;)

**Comment by vmg** [comment]
You're very much welcome. And yes, of course I looked for your real name. Social coding, remember? That's our business, it says that on the header. :)

Thanks again for reporting!

**Comment by franzliedke** [comment]
Way to make that reality, then, Vicent. Keep it up, you guys are doing an awesome job!
