### ISSUE TITLE
Hanging whitespace breaks tables

### ISSUE THREAD

**Issue by iramiller** [vmg/sundown#91]
When rendering a table if there is white space on the end of any of the lines the table does not render

```
| First Header  | Second Header | 
| ------------- | ------------- |  
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |
```

I am running sundown via  misaka on python 2.6.

**Comment by vmg** [comment]
Gotcha! Sorry for the delay, this should be fixed now. ^^

**Comment by iramiller** [comment]
Brilliant.  Thanks!
