### ISSUE TITLE
Links containing parentheses

### ISSUE THREAD

**Issue by mkrogh** [vmg/sundown#99]
Just observed that links to urls with parentheses makes sundown (and markdown) freak out.

Exhibit A:

```
[A nice link...](http://en.wikipedia.org/wiki/Pretend_(song) "some song")
```

Becomes: [A nice link...](http://en.wikipedia.org/wiki/Pretend_%28song%29)

The additional `"some song")` seems a bit wrong.  The behavior has also been observed in the [original markdown dingus](http://daringfireball.net/projects/markdown/dingus).

It seems like the stackoverflow team had [a similar experience](http://meta.stackoverflow.com/questions/13501/links-to-urls-containing-parentheses)

**Comment by vmg** [comment]
Hey Markus,

this is intended. Escape the parentheses in an URL so they don't act as delimiters.

```
[A nice link...](http://en.wikipedia.org/wiki/Pretend_\(song\) "some song")
```

[A nice link...](http://en.wikipedia.org/wiki/Pretend_%28song%29)

Cheers!

**Comment by mkrogh** [comment]
Fair enough if it is "intended", however it is something that is very hard to convince users to do.

**Comment by vmg** [comment]
I don't write the standard, I just implement it as closely as possible. I'm afraid I cannot change these things. Sorry!
